//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Finviz_Financials> Finviz_Financials { get; set; }
        public virtual DbSet<Finviz_Insider_Trading> Finviz_Insider_Trading { get; set; }
        public virtual DbSet<Finviz_Recommendations> Finviz_Recommendations { get; set; }
        public virtual DbSet<ft_Financials_MgmtEffectiveness> ft_Financials_MgmtEffectiveness { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Markets_Financials> Markets_Financials { get; set; }
        public virtual DbSet<Markets_Financials_Types> Markets_Financials_Types { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Reuters_Financials_Dividends> Reuters_Financials_Dividends { get; set; }
        public virtual DbSet<Reuters_Financials_Efficiencies> Reuters_Financials_Efficiencies { get; set; }
        public virtual DbSet<Reuters_Financials_GrowthRates> Reuters_Financials_GrowthRates { get; set; }
        public virtual DbSet<Reuters_Financials_Institutions> Reuters_Financials_Institutions { get; set; }
        public virtual DbSet<Reuters_Financials_MgmtEffectiveness> Reuters_Financials_MgmtEffectiveness { get; set; }
        public virtual DbSet<Reuters_Financials_ProfitabilityRatios> Reuters_Financials_ProfitabilityRatios { get; set; }
        public virtual DbSet<Reuters_Financials_SalesEstimates> Reuters_Financials_SalesEstimates { get; set; }
        public virtual DbSet<Reuters_Financials_Strength> Reuters_Financials_Strength { get; set; }
        public virtual DbSet<Reuters_Financials_ValuationRatios> Reuters_Financials_ValuationRatios { get; set; }
        public virtual DbSet<Reuters_RecommendationsRevisions> Reuters_RecommendationsRevisions { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
