//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<finviz_Calendar> finviz_Calendar { get; set; }
        public virtual DbSet<finviz_Financials> finviz_Financials { get; set; }
        public virtual DbSet<finviz_Insider_Trading> finviz_Insider_Trading { get; set; }
        public virtual DbSet<finviz_Market_Movers> finviz_Market_Movers { get; set; }
        public virtual DbSet<finviz_News> finviz_News { get; set; }
        public virtual DbSet<finviz_Recommendations> finviz_Recommendations { get; set; }
        public virtual DbSet<ft_Consensus> ft_Consensus { get; set; }
        public virtual DbSet<ft_Financials> ft_Financials { get; set; }
        public virtual DbSet<ft_Forecasts> ft_Forecasts { get; set; }
        public virtual DbSet<reuters_Financials_Dividends> reuters_Financials_Dividends { get; set; }
        public virtual DbSet<reuters_Financials_Efficiencies> reuters_Financials_Efficiencies { get; set; }
        public virtual DbSet<reuters_Financials_GrowthRates> reuters_Financials_GrowthRates { get; set; }
        public virtual DbSet<reuters_Financials_Institutions> reuters_Financials_Institutions { get; set; }
        public virtual DbSet<reuters_Financials_MgmtEffectiveness> reuters_Financials_MgmtEffectiveness { get; set; }
        public virtual DbSet<reuters_Financials_ProfitabilityRatios> reuters_Financials_ProfitabilityRatios { get; set; }
        public virtual DbSet<reuters_Financials_SalesEstimates> reuters_Financials_SalesEstimates { get; set; }
        public virtual DbSet<reuters_Financials_Strength> reuters_Financials_Strength { get; set; }
        public virtual DbSet<reuters_Financials_ValuationRatios> reuters_Financials_ValuationRatios { get; set; }
        public virtual DbSet<reuters_RecommendationsRevisions> reuters_RecommendationsRevisions { get; set; }
        public virtual DbSet<ws_JobRuns> ws_JobRuns { get; set; }
        public virtual DbSet<ws_Jobs> ws_Jobs { get; set; }
        public virtual DbSet<ws_JobScheduler> ws_JobScheduler { get; set; }
        public virtual DbSet<ws_JobScheduler_Daily> ws_JobScheduler_Daily { get; set; }
        public virtual DbSet<ws_JobScheduler_Monthly> ws_JobScheduler_Monthly { get; set; }
        public virtual DbSet<ws_JobScheduler_Weekly> ws_JobScheduler_Weekly { get; set; }
        public virtual DbSet<ws_JobScheduler_Yearly> ws_JobScheduler_Yearly { get; set; }
        public virtual DbSet<ws_Logs> ws_Logs { get; set; }
        public virtual DbSet<ws_Stocks> ws_Stocks { get; set; }
        public virtual DbSet<wslu_JobSchedulerTypes> wslu_JobSchedulerTypes { get; set; }
        public virtual DbSet<wslu_JobTypes> wslu_JobTypes { get; set; }
    
        public virtual ObjectResult<p_GetJobScheduler_Result> p_GetJobScheduler(Nullable<int> scheduler_id, string name)
        {
            var scheduler_idParameter = scheduler_id.HasValue ?
                new ObjectParameter("scheduler_id", scheduler_id) :
                new ObjectParameter("scheduler_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetJobScheduler_Result>("p_GetJobScheduler", scheduler_idParameter, nameParameter);
        }
    
        public virtual ObjectResult<p_GetAllFieldsForJobScheduler_Result> p_GetAllFieldsForJobScheduler(Nullable<int> scheduler_id)
        {
            var scheduler_idParameter = scheduler_id.HasValue ?
                new ObjectParameter("scheduler_id", scheduler_id) :
                new ObjectParameter("scheduler_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetAllFieldsForJobScheduler_Result>("p_GetAllFieldsForJobScheduler", scheduler_idParameter);
        }
    }
}
