//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fin_Market_Movers
    {
        public long Market_Movers_Id { get; set; }
        public int Job_run_Id { get; set; }
        public string Ticker { get; set; }
        public string Last { get; set; }
        public string Change { get; set; }
        public string Volume { get; set; }
        public string Signal { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
    }
}
