//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class finviz_Market_Movers
    {
        public long finviz_market_movers_id { get; set; }
        public int stock_id { get; set; }
        public int job_run_id { get; set; }
        public string EffectiveDate { get; set; }
        public string ticker { get; set; }
        public Nullable<decimal> last_quote { get; set; }
        public Nullable<decimal> percent_change { get; set; }
        public Nullable<int> volume { get; set; }
        public string signal { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
