//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class finviz_Calendar
    {
        public long finviz_calendar_id { get; set; }
        public int job_run_id { get; set; }
        public string calendar_date_text { get; set; }
        public string calendar_yyyy { get; set; }
        public string calendar_mm { get; set; }
        public string calendar_dd { get; set; }
        public string calendar_day { get; set; }
        public string banner_date { get; set; }
        public string time_zone { get; set; }
        public string calendar_date { get; set; }
        public Nullable<bool> market_closed { get; set; }
        public Nullable<bool> official_market_closure { get; set; }
        public string market_closure_notes { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
    }
}
