//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class finviz_Insider_Trading
    {
        public long Finviz_Insider_TradingId { get; set; }
        public int stock_Id { get; set; }
        public int Job_run_Id { get; set; }
        public string EffectiveDate { get; set; }
        public string insider_Trading { get; set; }
        public string relationship { get; set; }
        public string Date { get; set; }
        public string it_transaction { get; set; }
        public string cost { get; set; }
        public string shares { get; set; }
        public string value { get; set; }
        public string shares_Total { get; set; }
        public string SEC_Form_4 { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
