//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_Consensus
    {
        public long ConsensusId { get; set; }
        public int job_run_id { get; set; }
        public int stock_id { get; set; }
        public string effective_date { get; set; }
        public string consensus { get; set; }
        public Nullable<short> buy_analyst_count { get; set; }
        public Nullable<short> outperform_analyst_count { get; set; }
        public Nullable<short> hold_analyst_count { get; set; }
        public Nullable<short> underperform_analyst_count { get; set; }
        public Nullable<short> sell_analyst_count { get; set; }
        public Nullable<short> no_opinion_analyst_count { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
