//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_Forecasts
    {
        public long forecast_id { get; set; }
        public int job_run_id { get; set; }
        public int stock_id { get; set; }
        public string effective_date { get; set; }
        public string forecast_description { get; set; }
        public Nullable<decimal> current_price { get; set; }
        public Nullable<decimal> high_target_price { get; set; }
        public Nullable<decimal> medium_target_price { get; set; }
        public Nullable<decimal> low_target_price { get; set; }
        public string time_period_unit { get; set; }
        public Nullable<short> time_period { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
