//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_Financials
    {
        public long financial_id { get; set; }
        public int job_run_id { get; set; }
        public int stock_id { get; set; }
        public string effective_date { get; set; }
        public string year { get; set; }
        public Nullable<decimal> ragp_total_revenue { get; set; }
        public Nullable<decimal> oe_cost_of_revenue_total { get; set; }
        public Nullable<decimal> oe_selling_generalexpenses_total { get; set; }
        public Nullable<decimal> oe_depreciation_amort { get; set; }
        public Nullable<decimal> oe_unusual_expense_income { get; set; }
        public Nullable<decimal> oe_other_operating_expenses_total { get; set; }
        public Nullable<decimal> oe_total_operating_expense { get; set; }
        public Nullable<decimal> oe_operating_income { get; set; }
        public Nullable<decimal> oe_other_net { get; set; }
        public Nullable<decimal> itmiei_net_income_before_taxes { get; set; }
        public Nullable<decimal> itmiei_provision_for_income_taxes { get; set; }
        public Nullable<decimal> itmiei_net_income_after_taxes { get; set; }
        public Nullable<decimal> itmiei_minority_interest { get; set; }
        public Nullable<decimal> itmiei_net_income_before_extra_items { get; set; }
        public Nullable<decimal> itmiei_total_extraordinary_items { get; set; }
        public Nullable<decimal> itmiei_net_income { get; set; }
        public Nullable<decimal> itmiei_inc_to_common_excl_extra_items { get; set; }
        public Nullable<decimal> itmiei_inc_to_common_incl_extra_items { get; set; }
        public Nullable<decimal> epsr_basic_weighted_average_shares { get; set; }
        public Nullable<decimal> epsr_basic_eps_excl_extra_items { get; set; }
        public Nullable<decimal> epsr_basic_eps_incl_extra_items { get; set; }
        public Nullable<decimal> epsr_dilution_adjustment { get; set; }
        public Nullable<decimal> epsr_diluted_weighted_average_shares { get; set; }
        public Nullable<decimal> epsr_diluted_eps_excl_extra_items { get; set; }
        public Nullable<decimal> epsr_diluted_eps_incl_extra_items { get; set; }
        public Nullable<decimal> csd_dps_common_stock_primary_issue { get; set; }
        public Nullable<decimal> csd_gross_dividend_common_stock { get; set; }
        public Nullable<decimal> pfi_pro_forma_net_income { get; set; }
        public Nullable<decimal> pfi_interest_expense_supplemental { get; set; }
        public Nullable<decimal> si_depreciation_supplemental { get; set; }
        public Nullable<decimal> si_total_special_items { get; set; }
        public Nullable<decimal> ni_normalized_income_before_taxes { get; set; }
        public Nullable<decimal> ni_effect_of_special_items_on_income_taxes { get; set; }
        public Nullable<decimal> ni_income_tax_excluding_impact_of_special_items { get; set; }
        public Nullable<decimal> ni_normalized_income_after_tax { get; set; }
        public Nullable<decimal> ni_normalized_income_avail_to_common { get; set; }
        public Nullable<decimal> ni_basic_normalized_eps { get; set; }
        public Nullable<decimal> ni_diluted_normalized_eps { get; set; }
        public byte[] created_on { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
