//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_forecasts_recommendations
    {
        public long forecast_recommendation_Id { get; set; }
        public int job_run_id { get; set; }
        public int stock_id { get; set; }
        public string effective_date { get; set; }
        public string Recommendation_consensus { get; set; }
        public string Recommendation_type { get; set; }
        public Nullable<short> Recommendations { get; set; }
        public string Analyst { get; set; }
        public string Target { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_Jobs ws_Jobs { get; set; }
        public virtual ws_Stocks ws_Stocks { get; set; }
    }
}
