//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_Financials_MgmtEffectiveness
    {
        public long ft_Financials_MgmtEffectiveness_Id { get; set; }
        public int Stock_Id { get; set; }
        public int Job_Id { get; set; }
        public string EffectiveDate { get; set; }
        public string Company_Name { get; set; }
        public string Exchange { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public string Buy { get; set; }
        public string OutPerforms { get; set; }
        public string Hold { get; set; }
        public string UnderPerform { get; set; }
        public string Sell { get; set; }
        public string NoOpinion { get; set; }
        public string Share_Price_ForeCast { get; set; }
        public string High_Percentage { get; set; }
        public string High_Value { get; set; }
        public string Med_Percentage { get; set; }
        public string Med_Value { get; set; }
        public string Low_Percentage { get; set; }
        public string Low_Value { get; set; }
        public string CompanyDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Time_ST { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
