//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reuters_RecommendationsRevisions
    {
        public long Reuters_RecommendationsRevisions_Id { get; set; }
        public int Stock_Id { get; set; }
        public int Job_Id { get; set; }
        public Nullable<System.DateTime> LastRecommendationDate { get; set; }
        public string Linear_Scale { get; set; }
        public string AnalystRecommend_Current { get; set; }
        public string AnalystRecommend_Month_1 { get; set; }
        public string AnalystRecommend_Month_2 { get; set; }
        public string AnalystRecommend_Month_3 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] Time_TS { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
