//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_FailRecords
    {
        public long fail_record_id { get; set; }
        public int stock_id { get; set; }
        public int scheduler_id { get; set; }
        public int run_job_id { get; set; }
        public byte[] CreatedOn { get; set; }
    }
}
