//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_JobScheduler_Daily
    {
        public int schedule_daily_id { get; set; }
        public int scheduler_id { get; set; }
        public int recur_days { get; set; }
        public Nullable<bool> IsWeekDay { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ws_JobScheduler ws_JobScheduler { get; set; }
    }
}
