//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_JobScheduler
    {
        public ws_JobScheduler()
        {
            this.ws_Jobs = new HashSet<ws_Jobs>();
            this.ws_JobScheduler_Daily = new HashSet<ws_JobScheduler_Daily>();
            this.ws_JobScheduler_Monthly = new HashSet<ws_JobScheduler_Monthly>();
            this.ws_JobScheduler_Weekly = new HashSet<ws_JobScheduler_Weekly>();
            this.ws_JobScheduler_Yearly = new HashSet<ws_JobScheduler_Yearly>();
        }
    
        public int scheduler_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int jobtype_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public int schedulertype_id { get; set; }
        public int current_run_count { get; set; }
        public int max_run_count { get; set; }
        public bool Status { get; set; }
        public byte[] CreatedOn { get; set; }
    
        public virtual ICollection<ws_Jobs> ws_Jobs { get; set; }
        public virtual ICollection<ws_JobScheduler_Daily> ws_JobScheduler_Daily { get; set; }
        public virtual ICollection<ws_JobScheduler_Monthly> ws_JobScheduler_Monthly { get; set; }
        public virtual ICollection<ws_JobScheduler_Weekly> ws_JobScheduler_Weekly { get; set; }
        public virtual wslu_JobSchedulerTypes wslu_JobSchedulerTypes { get; set; }
        public virtual wslu_JobTypes wslu_JobTypes { get; set; }
        public virtual ICollection<ws_JobScheduler_Yearly> ws_JobScheduler_Yearly { get; set; }
    }
}
