//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ws_Stocks
    {
        public ws_Stocks()
        {
            this.finviz_Financials = new HashSet<finviz_Financials>();
            this.finviz_Insider_Trading = new HashSet<finviz_Insider_Trading>();
            this.finviz_News = new HashSet<finviz_News>();
            this.finviz_Recommendations = new HashSet<finviz_Recommendations>();
            this.ft_Consensus = new HashSet<ft_Consensus>();
            this.ft_Financials = new HashSet<ft_Financials>();
            this.ft_Forecasts = new HashSet<ft_Forecasts>();
            this.reuters_Financials_Dividends = new HashSet<reuters_Financials_Dividends>();
            this.reuters_Financials_Efficiencies = new HashSet<reuters_Financials_Efficiencies>();
            this.reuters_Financials_GrowthRates = new HashSet<reuters_Financials_GrowthRates>();
            this.reuters_Financials_Institutions = new HashSet<reuters_Financials_Institutions>();
            this.reuters_Financials_MgmtEffectiveness = new HashSet<reuters_Financials_MgmtEffectiveness>();
            this.reuters_Financials_ProfitabilityRatios = new HashSet<reuters_Financials_ProfitabilityRatios>();
            this.reuters_Financials_SalesEstimates = new HashSet<reuters_Financials_SalesEstimates>();
            this.reuters_Financials_Strength = new HashSet<reuters_Financials_Strength>();
            this.reuters_Financials_ValuationRatios = new HashSet<reuters_Financials_ValuationRatios>();
            this.reuters_RecommendationsRevisions = new HashSet<reuters_RecommendationsRevisions>();
        }
    
        public int Stock_Id { get; set; }
        public string Ticker { get; set; }
        public string Company_Name { get; set; }
        public string Exchange { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public string Exchange_Abbr { get; set; }
        public string Exchange_Letter { get; set; }
        public string Format_Issue_Symbol { get; set; }
        public Nullable<byte> StatusState_Id { get; set; }
        public string Source { get; set; }
        public string company_desc_finviz { get; set; }
        public string sub_sector { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] UpdatedOn { get; set; }
    
        public virtual ICollection<finviz_Financials> finviz_Financials { get; set; }
        public virtual ICollection<finviz_Insider_Trading> finviz_Insider_Trading { get; set; }
        public virtual ICollection<finviz_News> finviz_News { get; set; }
        public virtual ICollection<finviz_Recommendations> finviz_Recommendations { get; set; }
        public virtual ICollection<ft_Consensus> ft_Consensus { get; set; }
        public virtual ICollection<ft_Financials> ft_Financials { get; set; }
        public virtual ICollection<ft_Forecasts> ft_Forecasts { get; set; }
        public virtual ICollection<reuters_Financials_Dividends> reuters_Financials_Dividends { get; set; }
        public virtual ICollection<reuters_Financials_Efficiencies> reuters_Financials_Efficiencies { get; set; }
        public virtual ICollection<reuters_Financials_GrowthRates> reuters_Financials_GrowthRates { get; set; }
        public virtual ICollection<reuters_Financials_Institutions> reuters_Financials_Institutions { get; set; }
        public virtual ICollection<reuters_Financials_MgmtEffectiveness> reuters_Financials_MgmtEffectiveness { get; set; }
        public virtual ICollection<reuters_Financials_ProfitabilityRatios> reuters_Financials_ProfitabilityRatios { get; set; }
        public virtual ICollection<reuters_Financials_SalesEstimates> reuters_Financials_SalesEstimates { get; set; }
        public virtual ICollection<reuters_Financials_Strength> reuters_Financials_Strength { get; set; }
        public virtual ICollection<reuters_Financials_ValuationRatios> reuters_Financials_ValuationRatios { get; set; }
        public virtual ICollection<reuters_RecommendationsRevisions> reuters_RecommendationsRevisions { get; set; }
    }
}
