//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wslu_JobSchedulerTypes
    {
        public wslu_JobSchedulerTypes()
        {
            this.ws_JobScheduler = new HashSet<ws_JobScheduler>();
        }
    
        public int schedulertype_id { get; set; }
        public string schedulartype_name { get; set; }
    
        public virtual ICollection<ws_JobScheduler> ws_JobScheduler { get; set; }
    }
}
