//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketMover
    {
        public int Market_MoverId { get; set; }
        public string Ticker { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Data_Display { get; set; }
        public string Exchange { get; set; }
        public string Sector { get; set; }
        public string Industry { get; set; }
        public byte[] Update_TS { get; set; }
    }
}
